// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aggregation.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAggregatedProfile = `-- name: CreateAggregatedProfile :one
INSERT INTO aggregated_examination_profiles (
    examination_id,
    specialist_id,
    schema_version,
    aggregation_version,
    baseline_algorithm_version,
    status,
    generated_at,
    baseline_refreshed_at,
    baseline_exam_count,
    overall_score,
    overall_band,
    primary_metric_key,
    neutral_recommendation_placeholder
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING
    id,
    examination_id,
    specialist_id,
    schema_version,
    aggregation_version,
    baseline_algorithm_version,
    status,
    generated_at,
    baseline_refreshed_at,
    baseline_exam_count,
    overall_score,
    overall_band,
    primary_metric_key,
    neutral_recommendation_placeholder,
    created_at,
    updated_at
`

type CreateAggregatedProfileParams struct {
	ExaminationID                    int64
	SpecialistID                     int64
	SchemaVersion                    int32
	AggregationVersion               string
	BaselineAlgorithmVersion         string
	Status                           string
	GeneratedAt                      pgtype.Timestamptz
	BaselineRefreshedAt              pgtype.Timestamptz
	BaselineExamCount                int32
	OverallScore                     pgtype.Float8
	OverallBand                      pgtype.Text
	PrimaryMetricKey                 pgtype.Text
	NeutralRecommendationPlaceholder pgtype.Text
}

func (q *Queries) CreateAggregatedProfile(ctx context.Context, arg CreateAggregatedProfileParams) (AggregatedExaminationProfile, error) {
	row := q.db.QueryRow(ctx, createAggregatedProfile,
		arg.ExaminationID,
		arg.SpecialistID,
		arg.SchemaVersion,
		arg.AggregationVersion,
		arg.BaselineAlgorithmVersion,
		arg.Status,
		arg.GeneratedAt,
		arg.BaselineRefreshedAt,
		arg.BaselineExamCount,
		arg.OverallScore,
		arg.OverallBand,
		arg.PrimaryMetricKey,
		arg.NeutralRecommendationPlaceholder,
	)
	var i AggregatedExaminationProfile
	err := row.Scan(
		&i.ID,
		&i.ExaminationID,
		&i.SpecialistID,
		&i.SchemaVersion,
		&i.AggregationVersion,
		&i.BaselineAlgorithmVersion,
		&i.Status,
		&i.GeneratedAt,
		&i.BaselineRefreshedAt,
		&i.BaselineExamCount,
		&i.OverallScore,
		&i.OverallBand,
		&i.PrimaryMetricKey,
		&i.NeutralRecommendationPlaceholder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExaminationBaselineSnapshot = `-- name: CreateExaminationBaselineSnapshot :one
INSERT INTO examination_baseline_snapshots (
    examination_id,
    profile_id,
    algorithm_version,
    refreshed_at,
    general_delta,
    general_band,
    general_reference_population_version,
    personal_delta,
    personal_band,
    baseline_exam_count,
    update_eligible,
    update_reason
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING
    id,
    examination_id,
    profile_id,
    algorithm_version,
    refreshed_at,
    general_delta,
    general_band,
    general_reference_population_version,
    personal_delta,
    personal_band,
    baseline_exam_count,
    update_eligible,
    update_reason,
    created_at
`

type CreateExaminationBaselineSnapshotParams struct {
	ExaminationID                     int64
	ProfileID                         int64
	AlgorithmVersion                  string
	RefreshedAt                       pgtype.Timestamptz
	GeneralDelta                      float64
	GeneralBand                       string
	GeneralReferencePopulationVersion pgtype.Text
	PersonalDelta                     float64
	PersonalBand                      string
	BaselineExamCount                 int32
	UpdateEligible                    bool
	UpdateReason                      pgtype.Text
}

func (q *Queries) CreateExaminationBaselineSnapshot(ctx context.Context, arg CreateExaminationBaselineSnapshotParams) (ExaminationBaselineSnapshot, error) {
	row := q.db.QueryRow(ctx, createExaminationBaselineSnapshot,
		arg.ExaminationID,
		arg.ProfileID,
		arg.AlgorithmVersion,
		arg.RefreshedAt,
		arg.GeneralDelta,
		arg.GeneralBand,
		arg.GeneralReferencePopulationVersion,
		arg.PersonalDelta,
		arg.PersonalBand,
		arg.BaselineExamCount,
		arg.UpdateEligible,
		arg.UpdateReason,
	)
	var i ExaminationBaselineSnapshot
	err := row.Scan(
		&i.ID,
		&i.ExaminationID,
		&i.ProfileID,
		&i.AlgorithmVersion,
		&i.RefreshedAt,
		&i.GeneralDelta,
		&i.GeneralBand,
		&i.GeneralReferencePopulationVersion,
		&i.PersonalDelta,
		&i.PersonalBand,
		&i.BaselineExamCount,
		&i.UpdateEligible,
		&i.UpdateReason,
		&i.CreatedAt,
	)
	return i, err
}

const getAggregationReadiness = `-- name: GetAggregationReadiness :one
SELECT
    examinations.id AS examination_id,
    examinations.specialist_id,
    examinations.status,
    COUNT(channel_runs.id) AS channels_total,
    COUNT(*) FILTER (WHERE channel_runs.status = 'succeeded') AS channels_succeeded,
    EXISTS (
        SELECT 1
        FROM aggregated_examination_profiles profiles
        WHERE profiles.examination_id = examinations.id
    ) AS already_aggregated
FROM examinations
LEFT JOIN examination_channel_runs channel_runs
    ON channel_runs.examination_id = examinations.id
WHERE examinations.id = $1
GROUP BY examinations.id
`

type GetAggregationReadinessRow struct {
	ExaminationID     int64
	SpecialistID      int64
	Status            string
	ChannelsTotal     int64
	ChannelsSucceeded int64
	AlreadyAggregated bool
}

func (q *Queries) GetAggregationReadiness(ctx context.Context, id int64) (GetAggregationReadinessRow, error) {
	row := q.db.QueryRow(ctx, getAggregationReadiness, id)
	var i GetAggregationReadinessRow
	err := row.Scan(
		&i.ExaminationID,
		&i.SpecialistID,
		&i.Status,
		&i.ChannelsTotal,
		&i.ChannelsSucceeded,
		&i.AlreadyAggregated,
	)
	return i, err
}

const getSpecialistBaselineState = `-- name: GetSpecialistBaselineState :one
SELECT
    id,
    specialist_id,
    algorithm_version,
    refreshed_at,
    baseline_exam_count,
    update_eligible,
    update_reason,
    metrics,
    created_at,
    updated_at
FROM specialist_baseline_states
WHERE specialist_id = $1
`

func (q *Queries) GetSpecialistBaselineState(ctx context.Context, specialistID int64) (SpecialistBaselineState, error) {
	row := q.db.QueryRow(ctx, getSpecialistBaselineState, specialistID)
	var i SpecialistBaselineState
	err := row.Scan(
		&i.ID,
		&i.SpecialistID,
		&i.AlgorithmVersion,
		&i.RefreshedAt,
		&i.BaselineExamCount,
		&i.UpdateEligible,
		&i.UpdateReason,
		&i.Metrics,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAggregatedProfileContribution = `-- name: InsertAggregatedProfileContribution :one
INSERT INTO aggregated_profile_channel_contributions (
    profile_id,
    channel,
    metric_key,
    weight,
    contribution,
    evidence_keys
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, profile_id, channel, metric_key, weight, contribution, evidence_keys, created_at
`

type InsertAggregatedProfileContributionParams struct {
	ProfileID    int64
	Channel      string
	MetricKey    string
	Weight       float64
	Contribution float64
	EvidenceKeys []byte
}

func (q *Queries) InsertAggregatedProfileContribution(ctx context.Context, arg InsertAggregatedProfileContributionParams) (AggregatedProfileChannelContribution, error) {
	row := q.db.QueryRow(ctx, insertAggregatedProfileContribution,
		arg.ProfileID,
		arg.Channel,
		arg.MetricKey,
		arg.Weight,
		arg.Contribution,
		arg.EvidenceKeys,
	)
	var i AggregatedProfileChannelContribution
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Channel,
		&i.MetricKey,
		&i.Weight,
		&i.Contribution,
		&i.EvidenceKeys,
		&i.CreatedAt,
	)
	return i, err
}

const insertAggregatedProfileExplanation = `-- name: InsertAggregatedProfileExplanation :one
INSERT INTO aggregated_profile_explanations (
    profile_id,
    position,
    kind,
    text
)
VALUES ($1, $2, $3, $4)
RETURNING id, profile_id, position, kind, text, created_at
`

type InsertAggregatedProfileExplanationParams struct {
	ProfileID int64
	Position  int32
	Kind      string
	Text      string
}

func (q *Queries) InsertAggregatedProfileExplanation(ctx context.Context, arg InsertAggregatedProfileExplanationParams) (AggregatedProfileExplanation, error) {
	row := q.db.QueryRow(ctx, insertAggregatedProfileExplanation,
		arg.ProfileID,
		arg.Position,
		arg.Kind,
		arg.Text,
	)
	var i AggregatedProfileExplanation
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Position,
		&i.Kind,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const insertAggregatedProfileMetric = `-- name: InsertAggregatedProfileMetric :one
INSERT INTO aggregated_profile_metrics (
    profile_id,
    metric_key,
    label,
    value,
    scale,
    direction
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, profile_id, metric_key, label, value, scale, direction, created_at
`

type InsertAggregatedProfileMetricParams struct {
	ProfileID int64
	MetricKey string
	Label     string
	Value     float64
	Scale     string
	Direction string
}

func (q *Queries) InsertAggregatedProfileMetric(ctx context.Context, arg InsertAggregatedProfileMetricParams) (AggregatedProfileMetric, error) {
	row := q.db.QueryRow(ctx, insertAggregatedProfileMetric,
		arg.ProfileID,
		arg.MetricKey,
		arg.Label,
		arg.Value,
		arg.Scale,
		arg.Direction,
	)
	var i AggregatedProfileMetric
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.MetricKey,
		&i.Label,
		&i.Value,
		&i.Scale,
		&i.Direction,
		&i.CreatedAt,
	)
	return i, err
}

const listSpecialistResultHistory = `-- name: ListSpecialistResultHistory :many
SELECT
    profiles.examination_id,
    profiles.specialist_id,
    profiles.generated_at,
    profiles.status,
    profiles.schema_version,
    profiles.aggregation_version,
    profiles.overall_score,
    profiles.overall_band,
    profiles.primary_metric_key,
    baseline.algorithm_version AS baseline_algorithm_version,
    baseline.refreshed_at AS baseline_refreshed_at,
    baseline.general_delta,
    baseline.personal_delta,
    baseline.baseline_exam_count
FROM aggregated_examination_profiles profiles
LEFT JOIN examination_baseline_snapshots baseline
    ON baseline.profile_id = profiles.id
WHERE profiles.specialist_id = $1
ORDER BY profiles.generated_at DESC, profiles.id DESC
`

type ListSpecialistResultHistoryRow struct {
	ExaminationID            int64
	SpecialistID             int64
	GeneratedAt              pgtype.Timestamptz
	Status                   string
	SchemaVersion            int32
	AggregationVersion       string
	OverallScore             pgtype.Float8
	OverallBand              pgtype.Text
	PrimaryMetricKey         pgtype.Text
	BaselineAlgorithmVersion pgtype.Text
	BaselineRefreshedAt      pgtype.Timestamptz
	GeneralDelta             pgtype.Float8
	PersonalDelta            pgtype.Float8
	BaselineExamCount        pgtype.Int4
}

func (q *Queries) ListSpecialistResultHistory(ctx context.Context, specialistID int64) ([]ListSpecialistResultHistoryRow, error) {
	rows, err := q.db.Query(ctx, listSpecialistResultHistory, specialistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpecialistResultHistoryRow
	for rows.Next() {
		var i ListSpecialistResultHistoryRow
		if err := rows.Scan(
			&i.ExaminationID,
			&i.SpecialistID,
			&i.GeneratedAt,
			&i.Status,
			&i.SchemaVersion,
			&i.AggregationVersion,
			&i.OverallScore,
			&i.OverallBand,
			&i.PrimaryMetricKey,
			&i.BaselineAlgorithmVersion,
			&i.BaselineRefreshedAt,
			&i.GeneralDelta,
			&i.PersonalDelta,
			&i.BaselineExamCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExaminationAggregated = `-- name: MarkExaminationAggregated :one
UPDATE examinations
SET
    status = 'aggregated',
    updated_at = NOW()
WHERE id = $1
RETURNING id, specialist_id, created_by_user_id, questionnaire_id, status, created_at, started_at, finished_at, updated_at
`

type MarkExaminationAggregatedRow struct {
	ID              int64
	SpecialistID    int64
	CreatedByUserID int64
	QuestionnaireID pgtype.Int8
	Status          string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) MarkExaminationAggregated(ctx context.Context, id int64) (MarkExaminationAggregatedRow, error) {
	row := q.db.QueryRow(ctx, markExaminationAggregated, id)
	var i MarkExaminationAggregatedRow
	err := row.Scan(
		&i.ID,
		&i.SpecialistID,
		&i.CreatedByUserID,
		&i.QuestionnaireID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markExaminationAggregating = `-- name: MarkExaminationAggregating :one
UPDATE examinations
SET
    status = 'aggregating',
    updated_at = NOW()
WHERE id = $1
RETURNING id, specialist_id, created_by_user_id, questionnaire_id, status, created_at, started_at, finished_at, updated_at
`

type MarkExaminationAggregatingRow struct {
	ID              int64
	SpecialistID    int64
	CreatedByUserID int64
	QuestionnaireID pgtype.Int8
	Status          string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) MarkExaminationAggregating(ctx context.Context, id int64) (MarkExaminationAggregatingRow, error) {
	row := q.db.QueryRow(ctx, markExaminationAggregating, id)
	var i MarkExaminationAggregatingRow
	err := row.Scan(
		&i.ID,
		&i.SpecialistID,
		&i.CreatedByUserID,
		&i.QuestionnaireID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSpecialistBaselineState = `-- name: UpsertSpecialistBaselineState :one
INSERT INTO specialist_baseline_states (
    specialist_id,
    algorithm_version,
    refreshed_at,
    baseline_exam_count,
    update_eligible,
    update_reason,
    metrics
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (specialist_id) DO UPDATE
SET
    algorithm_version = EXCLUDED.algorithm_version,
    refreshed_at = EXCLUDED.refreshed_at,
    baseline_exam_count = EXCLUDED.baseline_exam_count,
    update_eligible = EXCLUDED.update_eligible,
    update_reason = EXCLUDED.update_reason,
    metrics = EXCLUDED.metrics,
    updated_at = NOW()
RETURNING
    id,
    specialist_id,
    algorithm_version,
    refreshed_at,
    baseline_exam_count,
    update_eligible,
    update_reason,
    metrics,
    created_at,
    updated_at
`

type UpsertSpecialistBaselineStateParams struct {
	SpecialistID      int64
	AlgorithmVersion  string
	RefreshedAt       pgtype.Timestamptz
	BaselineExamCount int32
	UpdateEligible    bool
	UpdateReason      pgtype.Text
	Metrics           []byte
}

func (q *Queries) UpsertSpecialistBaselineState(ctx context.Context, arg UpsertSpecialistBaselineStateParams) (SpecialistBaselineState, error) {
	row := q.db.QueryRow(ctx, upsertSpecialistBaselineState,
		arg.SpecialistID,
		arg.AlgorithmVersion,
		arg.RefreshedAt,
		arg.BaselineExamCount,
		arg.UpdateEligible,
		arg.UpdateReason,
		arg.Metrics,
	)
	var i SpecialistBaselineState
	err := row.Scan(
		&i.ID,
		&i.SpecialistID,
		&i.AlgorithmVersion,
		&i.RefreshedAt,
		&i.BaselineExamCount,
		&i.UpdateEligible,
		&i.UpdateReason,
		&i.Metrics,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
