// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: answers.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnswer = `-- name: CreateAnswer :one
INSERT INTO answers (
    id,
    examination_id,
    examination_question_id,
    specialist_id,
    created_by_user_id,
    answer_text,
    audio_s3_key
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, examination_id, examination_question_id, specialist_id, created_by_user_id, answer_text, audio_s3_key, created_at
`

type CreateAnswerParams struct {
	ID                    int64
	ExaminationID         int64
	ExaminationQuestionID pgtype.Int8
	SpecialistID          pgtype.Int8
	CreatedByUserID       int64
	AnswerText            string
	AudioS3Key            string
}

type CreateAnswerRow struct {
	ID                    int64
	ExaminationID         int64
	ExaminationQuestionID pgtype.Int8
	SpecialistID          pgtype.Int8
	CreatedByUserID       int64
	AnswerText            string
	AudioS3Key            string
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (CreateAnswerRow, error) {
	row := q.db.QueryRow(ctx, createAnswer,
		arg.ID,
		arg.ExaminationID,
		arg.ExaminationQuestionID,
		arg.SpecialistID,
		arg.CreatedByUserID,
		arg.AnswerText,
		arg.AudioS3Key,
	)
	var i CreateAnswerRow
	err := row.Scan(
		&i.ID,
		&i.ExaminationID,
		&i.ExaminationQuestionID,
		&i.SpecialistID,
		&i.CreatedByUserID,
		&i.AnswerText,
		&i.AudioS3Key,
		&i.CreatedAt,
	)
	return i, err
}

const getExaminationQuestionByID = `-- name: GetExaminationQuestionByID :one
SELECT id, examination_id, specialist_id, questionnaire_id, source_question_id, position, question_text
FROM examination_questions
WHERE id = $1
`

func (q *Queries) GetExaminationQuestionByID(ctx context.Context, id int64) (ExaminationQuestion, error) {
	row := q.db.QueryRow(ctx, getExaminationQuestionByID, id)
	var i ExaminationQuestion
	err := row.Scan(
		&i.ID,
		&i.ExaminationID,
		&i.SpecialistID,
		&i.QuestionnaireID,
		&i.SourceQuestionID,
		&i.Position,
		&i.QuestionText,
	)
	return i, err
}

const nextAnswerID = `-- name: NextAnswerID :one
SELECT nextval('answers_id_seq')
`

func (q *Queries) NextAnswerID(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextAnswerID)
	var nextval int64
	err := row.Scan(&nextval)
	return nextval, err
}
