// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    event_type,
    event_key,
    outcome,
    happened_at,
    request_id,
    trace_id,
    traceparent,
    tracestate,
    correlation_id,
    actor_user_id,
    actor_login,
    actor_role_slug,
    actor_ip,
    actor_user_agent,
    resource_kind,
    resource_id,
    examination_id,
    specialist_id,
    questionnaire_id,
    channel,
    decision_snapshot_id,
    payload
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15, $16, $17, $18,
    $19, $20, $21, $22
)
ON CONFLICT (event_key) WHERE event_key IS NOT NULL DO NOTHING
RETURNING id, event_type, event_key, outcome, happened_at, request_id, trace_id, traceparent, tracestate, correlation_id, actor_user_id, actor_login, actor_role_slug, actor_ip, actor_user_agent, resource_kind, resource_id, examination_id, specialist_id, questionnaire_id, channel, decision_snapshot_id, payload, created_at
`

type CreateAuditLogParams struct {
	EventType          string
	EventKey           pgtype.Text
	Outcome            string
	HappenedAt         pgtype.Timestamptz
	RequestID          pgtype.Text
	TraceID            pgtype.Text
	Traceparent        pgtype.Text
	Tracestate         pgtype.Text
	CorrelationID      pgtype.Text
	ActorUserID        pgtype.Int8
	ActorLogin         pgtype.Text
	ActorRoleSlug      pgtype.Text
	ActorIp            pgtype.Text
	ActorUserAgent     pgtype.Text
	ResourceKind       string
	ResourceID         pgtype.Int8
	ExaminationID      pgtype.Int8
	SpecialistID       pgtype.Int8
	QuestionnaireID    pgtype.Int8
	Channel            pgtype.Text
	DecisionSnapshotID pgtype.Int8
	Payload            []byte
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.EventType,
		arg.EventKey,
		arg.Outcome,
		arg.HappenedAt,
		arg.RequestID,
		arg.TraceID,
		arg.Traceparent,
		arg.Tracestate,
		arg.CorrelationID,
		arg.ActorUserID,
		arg.ActorLogin,
		arg.ActorRoleSlug,
		arg.ActorIp,
		arg.ActorUserAgent,
		arg.ResourceKind,
		arg.ResourceID,
		arg.ExaminationID,
		arg.SpecialistID,
		arg.QuestionnaireID,
		arg.Channel,
		arg.DecisionSnapshotID,
		arg.Payload,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.EventKey,
		&i.Outcome,
		&i.HappenedAt,
		&i.RequestID,
		&i.TraceID,
		&i.Traceparent,
		&i.Tracestate,
		&i.CorrelationID,
		&i.ActorUserID,
		&i.ActorLogin,
		&i.ActorRoleSlug,
		&i.ActorIp,
		&i.ActorUserAgent,
		&i.ResourceKind,
		&i.ResourceID,
		&i.ExaminationID,
		&i.SpecialistID,
		&i.QuestionnaireID,
		&i.Channel,
		&i.DecisionSnapshotID,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, event_type, event_key, outcome, happened_at, request_id, trace_id, traceparent, tracestate, correlation_id, actor_user_id, actor_login, actor_role_slug, actor_ip, actor_user_agent, resource_kind, resource_id, examination_id, specialist_id, questionnaire_id, channel, decision_snapshot_id, payload, created_at
FROM audit_logs
WHERE
    ($1::text IS NULL OR event_type = $1::text)
    AND ($2::text IS NULL OR resource_kind = $2::text)
    AND ($3::bigint IS NULL OR resource_id = $3::bigint)
    AND ($4::bigint IS NULL OR actor_user_id = $4::bigint)
    AND ($5::bigint IS NULL OR examination_id = $5::bigint)
    AND happened_at >= $6
    AND happened_at <= $7
ORDER BY happened_at DESC
LIMIT $8
`

type ListAuditLogsParams struct {
	EventType     pgtype.Text
	ResourceKind  pgtype.Text
	ResourceID    pgtype.Int8
	ActorUserID   pgtype.Int8
	ExaminationID pgtype.Int8
	FromAt        pgtype.Timestamptz
	ToAt          pgtype.Timestamptz
	LimitCount    int32
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.EventType,
		arg.ResourceKind,
		arg.ResourceID,
		arg.ActorUserID,
		arg.ExaminationID,
		arg.FromAt,
		arg.ToAt,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.EventKey,
			&i.Outcome,
			&i.HappenedAt,
			&i.RequestID,
			&i.TraceID,
			&i.Traceparent,
			&i.Tracestate,
			&i.CorrelationID,
			&i.ActorUserID,
			&i.ActorLogin,
			&i.ActorRoleSlug,
			&i.ActorIp,
			&i.ActorUserAgent,
			&i.ResourceKind,
			&i.ResourceID,
			&i.ExaminationID,
			&i.SpecialistID,
			&i.QuestionnaireID,
			&i.Channel,
			&i.DecisionSnapshotID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
