// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshSession = `-- name: CreateRefreshSession :one
INSERT INTO refresh_sessions (
    user_id,
    token_hash,
    expires_at,
    created_by_ip,
    user_agent,
    last_used_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, token_hash, expires_at, revoked_at, replaced_by_session_id, created_by_ip, user_agent, last_used_at, created_at
`

type CreateRefreshSessionParams struct {
	UserID      int64
	TokenHash   []byte
	ExpiresAt   pgtype.Timestamptz
	CreatedByIp pgtype.Text
	UserAgent   pgtype.Text
	LastUsedAt  pgtype.Timestamptz
}

func (q *Queries) CreateRefreshSession(ctx context.Context, arg CreateRefreshSessionParams) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, createRefreshSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedByIp,
		arg.UserAgent,
		arg.LastUsedAt,
	)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBySessionID,
		&i.CreatedByIp,
		&i.UserAgent,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    login,
    password_hash,
    role_id,
    is_active
) VALUES (
    $1, $2, $3, TRUE
)
RETURNING id, login, password_hash, role_id, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Login        string
	PasswordHash string
	RoleID       int64
}

type CreateUserRow struct {
	ID           int64
	Login        string
	PasswordHash string
	RoleID       int64
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Login, arg.PasswordHash, arg.RoleID)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRefreshSessionByHash = `-- name: GetRefreshSessionByHash :one
SELECT
    id,
    user_id,
    token_hash,
    expires_at,
    revoked_at,
    replaced_by_session_id,
    created_by_ip,
    user_agent,
    last_used_at,
    created_at
FROM refresh_sessions
WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) GetRefreshSessionByHash(ctx context.Context, tokenHash []byte) (RefreshSession, error) {
	row := q.db.QueryRow(ctx, getRefreshSessionByHash, tokenHash)
	var i RefreshSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBySessionID,
		&i.CreatedByIp,
		&i.UserAgent,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRoleBySlug = `-- name: GetRoleBySlug :one
SELECT id, slug, name, created_at
FROM roles
WHERE slug = $1
`

func (q *Queries) GetRoleBySlug(ctx context.Context, slug string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleBySlug, slug)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    u.id,
    u.login,
    u.password_hash,
    u.is_active,
    u.last_login_at,
    u.created_at,
    u.updated_at,
    r.id AS role_id,
    r.slug AS role_slug,
    r.name AS role_name,
    r.created_at AS role_created_at
FROM users u
JOIN roles r ON r.id = u.role_id
WHERE u.id = $1
`

type GetUserByIDRow struct {
	ID            int64
	Login         string
	PasswordHash  string
	IsActive      bool
	LastLoginAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	RoleID        int64
	RoleSlug      string
	RoleName      string
	RoleCreatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleID,
		&i.RoleSlug,
		&i.RoleName,
		&i.RoleCreatedAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT
    u.id,
    u.login,
    u.password_hash,
    u.is_active,
    u.last_login_at,
    u.created_at,
    u.updated_at,
    r.id AS role_id,
    r.slug AS role_slug,
    r.name AS role_name,
    r.created_at AS role_created_at
FROM users u
JOIN roles r ON r.id = u.role_id
WHERE u.login = $1
`

type GetUserByLoginRow struct {
	ID            int64
	Login         string
	PasswordHash  string
	IsActive      bool
	LastLoginAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	RoleID        int64
	RoleSlug      string
	RoleName      string
	RoleCreatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (GetUserByLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i GetUserByLoginRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleID,
		&i.RoleSlug,
		&i.RoleName,
		&i.RoleCreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    u.id,
    u.login,
    u.password_hash,
    u.is_active,
    u.last_login_at,
    u.created_at,
    u.updated_at,
    r.id AS role_id,
    r.slug AS role_slug,
    r.name AS role_name,
    r.created_at AS role_created_at
FROM users u
JOIN roles r ON r.id = u.role_id
ORDER BY u.id
`

type ListUsersRow struct {
	ID            int64
	Login         string
	PasswordHash  string
	IsActive      bool
	LastLoginAt   pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	RoleID        int64
	RoleSlug      string
	RoleName      string
	RoleCreatedAt pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Login,
			&i.PasswordHash,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RoleID,
			&i.RoleSlug,
			&i.RoleName,
			&i.RoleCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshSession = `-- name: RevokeRefreshSession :exec
UPDATE refresh_sessions
SET
    revoked_at = $2
WHERE id = $1
`

type RevokeRefreshSessionParams struct {
	ID        int64
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeRefreshSession(ctx context.Context, arg RevokeRefreshSessionParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshSession, arg.ID, arg.RevokedAt)
	return err
}

const rotateRefreshSession = `-- name: RotateRefreshSession :exec
UPDATE refresh_sessions
SET
    revoked_at = $2,
    replaced_by_session_id = $3,
    last_used_at = $4
WHERE id = $1
`

type RotateRefreshSessionParams struct {
	ID                  int64
	RevokedAt           pgtype.Timestamptz
	ReplacedBySessionID pgtype.Int8
	LastUsedAt          pgtype.Timestamptz
}

func (q *Queries) RotateRefreshSession(ctx context.Context, arg RotateRefreshSessionParams) error {
	_, err := q.db.Exec(ctx, rotateRefreshSession,
		arg.ID,
		arg.RevokedAt,
		arg.ReplacedBySessionID,
		arg.LastUsedAt,
	)
	return err
}

const touchRefreshSession = `-- name: TouchRefreshSession :exec
UPDATE refresh_sessions
SET
    last_used_at = $2
WHERE id = $1
`

type TouchRefreshSessionParams struct {
	ID         int64
	LastUsedAt pgtype.Timestamptz
}

func (q *Queries) TouchRefreshSession(ctx context.Context, arg TouchRefreshSessionParams) error {
	_, err := q.db.Exec(ctx, touchRefreshSession, arg.ID, arg.LastUsedAt)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    login = $2,
    role_id = $3,
    is_active = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, login, password_hash, role_id, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	ID       int64
	Login    string
	RoleID   int64
	IsActive bool
}

type UpdateUserRow struct {
	ID           int64
	Login        string
	PasswordHash string
	RoleID       int64
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Login,
		arg.RoleID,
		arg.IsActive,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET
    last_login_at = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserLastLoginParams struct {
	ID          int64
	LastLoginAt pgtype.Timestamptz
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, arg.ID, arg.LastLoginAt)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (
    login,
    password_hash,
    role_id,
    is_active
) VALUES (
    $1, $2, $3, TRUE
)
ON CONFLICT (login) DO UPDATE
SET
    password_hash = EXCLUDED.password_hash,
    role_id = EXCLUDED.role_id,
    is_active = TRUE,
    updated_at = NOW()
RETURNING id, login, password_hash, role_id, is_active, created_at, updated_at
`

type UpsertUserParams struct {
	Login        string
	PasswordHash string
	RoleID       int64
}

type UpsertUserRow struct {
	ID           int64
	Login        string
	PasswordHash string
	RoleID       int64
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (UpsertUserRow, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.Login, arg.PasswordHash, arg.RoleID)
	var i UpsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
