// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: decision.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDecisionSnapshot = `-- name: CreateDecisionSnapshot :one
INSERT INTO decision_snapshots (
    examination_id,
    specialist_id,
    status,
    payload_version,
    aggregation_version,
    recommendation,
    message,
    correlation_id,
    max_attempts,
    attempt_count,
    last_attempt_at,
    completed_at,
    diagnostics_json,
    raw_response_json
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING
    id,
    examination_id,
    specialist_id,
    status,
    payload_version,
    aggregation_version,
    recommendation,
    message,
    correlation_id,
    max_attempts,
    attempt_count,
    last_attempt_at,
    completed_at,
    diagnostics_json,
    raw_response_json,
    created_at,
    updated_at
`

type CreateDecisionSnapshotParams struct {
	ExaminationID      int64
	SpecialistID       int64
	Status             string
	PayloadVersion     string
	AggregationVersion string
	Recommendation     string
	Message            string
	CorrelationID      pgtype.Text
	MaxAttempts        int32
	AttemptCount       int32
	LastAttemptAt      pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	DiagnosticsJson    []byte
	RawResponseJson    []byte
}

func (q *Queries) CreateDecisionSnapshot(ctx context.Context, arg CreateDecisionSnapshotParams) (DecisionSnapshot, error) {
	row := q.db.QueryRow(ctx, createDecisionSnapshot,
		arg.ExaminationID,
		arg.SpecialistID,
		arg.Status,
		arg.PayloadVersion,
		arg.AggregationVersion,
		arg.Recommendation,
		arg.Message,
		arg.CorrelationID,
		arg.MaxAttempts,
		arg.AttemptCount,
		arg.LastAttemptAt,
		arg.CompletedAt,
		arg.DiagnosticsJson,
		arg.RawResponseJson,
	)
	var i DecisionSnapshot
	err := row.Scan(
		&i.ID,
		&i.ExaminationID,
		&i.SpecialistID,
		&i.Status,
		&i.PayloadVersion,
		&i.AggregationVersion,
		&i.Recommendation,
		&i.Message,
		&i.CorrelationID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.CompletedAt,
		&i.DiagnosticsJson,
		&i.RawResponseJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDecisionSnapshotByExamination = `-- name: GetDecisionSnapshotByExamination :one
SELECT
    id,
    examination_id,
    specialist_id,
    status,
    payload_version,
    aggregation_version,
    recommendation,
    message,
    correlation_id,
    max_attempts,
    attempt_count,
    last_attempt_at,
    completed_at,
    diagnostics_json,
    raw_response_json,
    created_at,
    updated_at
FROM decision_snapshots
WHERE examination_id = $1
`

func (q *Queries) GetDecisionSnapshotByExamination(ctx context.Context, examinationID int64) (DecisionSnapshot, error) {
	row := q.db.QueryRow(ctx, getDecisionSnapshotByExamination, examinationID)
	var i DecisionSnapshot
	err := row.Scan(
		&i.ID,
		&i.ExaminationID,
		&i.SpecialistID,
		&i.Status,
		&i.PayloadVersion,
		&i.AggregationVersion,
		&i.Recommendation,
		&i.Message,
		&i.CorrelationID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.CompletedAt,
		&i.DiagnosticsJson,
		&i.RawResponseJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExaminationDecisionProjection = `-- name: GetExaminationDecisionProjection :one
SELECT
    examinations.id AS examination_id,
    examinations.status AS examination_status,
    snapshots.id AS decision_snapshot_id,
    snapshots.status AS decision_status,
    snapshots.recommendation,
    snapshots.message,
    snapshots.correlation_id,
    snapshots.attempt_count,
    snapshots.max_attempts,
    snapshots.last_attempt_at,
    snapshots.completed_at,
    snapshots.diagnostics_json,
    (snapshots.raw_response_json IS NOT NULL) AS raw_response_available
FROM examinations
LEFT JOIN decision_snapshots snapshots
    ON snapshots.examination_id = examinations.id
WHERE examinations.id = $1
`

type GetExaminationDecisionProjectionRow struct {
	ExaminationID        int64
	ExaminationStatus    string
	DecisionSnapshotID   pgtype.Int8
	DecisionStatus       pgtype.Text
	Recommendation       pgtype.Text
	Message              pgtype.Text
	CorrelationID        pgtype.Text
	AttemptCount         pgtype.Int4
	MaxAttempts          pgtype.Int4
	LastAttemptAt        pgtype.Timestamptz
	CompletedAt          pgtype.Timestamptz
	DiagnosticsJson      []byte
	RawResponseAvailable interface{}
}

func (q *Queries) GetExaminationDecisionProjection(ctx context.Context, id int64) (GetExaminationDecisionProjectionRow, error) {
	row := q.db.QueryRow(ctx, getExaminationDecisionProjection, id)
	var i GetExaminationDecisionProjectionRow
	err := row.Scan(
		&i.ExaminationID,
		&i.ExaminationStatus,
		&i.DecisionSnapshotID,
		&i.DecisionStatus,
		&i.Recommendation,
		&i.Message,
		&i.CorrelationID,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LastAttemptAt,
		&i.CompletedAt,
		&i.DiagnosticsJson,
		&i.RawResponseAvailable,
	)
	return i, err
}

const incrementDecisionAttemptCount = `-- name: IncrementDecisionAttemptCount :one
UPDATE decision_snapshots
SET
    attempt_count = attempt_count + 1,
    correlation_id = $2,
    last_attempt_at = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    examination_id,
    specialist_id,
    status,
    payload_version,
    aggregation_version,
    recommendation,
    message,
    correlation_id,
    max_attempts,
    attempt_count,
    last_attempt_at,
    completed_at,
    diagnostics_json,
    raw_response_json,
    created_at,
    updated_at
`

type IncrementDecisionAttemptCountParams struct {
	ID            int64
	CorrelationID pgtype.Text
	LastAttemptAt pgtype.Timestamptz
}

func (q *Queries) IncrementDecisionAttemptCount(ctx context.Context, arg IncrementDecisionAttemptCountParams) (DecisionSnapshot, error) {
	row := q.db.QueryRow(ctx, incrementDecisionAttemptCount, arg.ID, arg.CorrelationID, arg.LastAttemptAt)
	var i DecisionSnapshot
	err := row.Scan(
		&i.ID,
		&i.ExaminationID,
		&i.SpecialistID,
		&i.Status,
		&i.PayloadVersion,
		&i.AggregationVersion,
		&i.Recommendation,
		&i.Message,
		&i.CorrelationID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.CompletedAt,
		&i.DiagnosticsJson,
		&i.RawResponseJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDecisionAttempt = `-- name: InsertDecisionAttempt :one
INSERT INTO decision_attempts (
    decision_snapshot_id,
    attempt_number,
    correlation_id,
    request_payload_json,
    response_payload_json,
    error_code,
    error_message,
    error_class,
    retryable,
    http_status,
    started_at,
    finished_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING
    id,
    decision_snapshot_id,
    attempt_number,
    correlation_id,
    request_payload_json,
    response_payload_json,
    error_code,
    error_message,
    error_class,
    retryable,
    http_status,
    started_at,
    finished_at,
    created_at
`

type InsertDecisionAttemptParams struct {
	DecisionSnapshotID  int64
	AttemptNumber       int32
	CorrelationID       pgtype.Text
	RequestPayloadJson  []byte
	ResponsePayloadJson []byte
	ErrorCode           pgtype.Text
	ErrorMessage        pgtype.Text
	ErrorClass          pgtype.Text
	Retryable           bool
	HttpStatus          pgtype.Int4
	StartedAt           pgtype.Timestamptz
	FinishedAt          pgtype.Timestamptz
}

func (q *Queries) InsertDecisionAttempt(ctx context.Context, arg InsertDecisionAttemptParams) (DecisionAttempt, error) {
	row := q.db.QueryRow(ctx, insertDecisionAttempt,
		arg.DecisionSnapshotID,
		arg.AttemptNumber,
		arg.CorrelationID,
		arg.RequestPayloadJson,
		arg.ResponsePayloadJson,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ErrorClass,
		arg.Retryable,
		arg.HttpStatus,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i DecisionAttempt
	err := row.Scan(
		&i.ID,
		&i.DecisionSnapshotID,
		&i.AttemptNumber,
		&i.CorrelationID,
		&i.RequestPayloadJson,
		&i.ResponsePayloadJson,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ErrorClass,
		&i.Retryable,
		&i.HttpStatus,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPendingDecisionSnapshots = `-- name: ListPendingDecisionSnapshots :many
SELECT
    id,
    examination_id,
    specialist_id,
    status,
    payload_version,
    aggregation_version,
    recommendation,
    message,
    correlation_id,
    max_attempts,
    attempt_count,
    last_attempt_at,
    completed_at,
    diagnostics_json,
    raw_response_json,
    created_at,
    updated_at
FROM decision_snapshots
WHERE status = 'pending'
ORDER BY updated_at ASC, id ASC
`

func (q *Queries) ListPendingDecisionSnapshots(ctx context.Context) ([]DecisionSnapshot, error) {
	rows, err := q.db.Query(ctx, listPendingDecisionSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DecisionSnapshot
	for rows.Next() {
		var i DecisionSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.ExaminationID,
			&i.SpecialistID,
			&i.Status,
			&i.PayloadVersion,
			&i.AggregationVersion,
			&i.Recommendation,
			&i.Message,
			&i.CorrelationID,
			&i.MaxAttempts,
			&i.AttemptCount,
			&i.LastAttemptAt,
			&i.CompletedAt,
			&i.DiagnosticsJson,
			&i.RawResponseJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDecisionAttemptFailed = `-- name: MarkDecisionAttemptFailed :one
UPDATE decision_snapshots
SET
    status = $2,
    recommendation = $3,
    message = $4,
    correlation_id = $5,
    attempt_count = $6,
    last_attempt_at = $7,
    completed_at = $8,
    diagnostics_json = $9,
    raw_response_json = $10,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    examination_id,
    specialist_id,
    status,
    payload_version,
    aggregation_version,
    recommendation,
    message,
    correlation_id,
    max_attempts,
    attempt_count,
    last_attempt_at,
    completed_at,
    diagnostics_json,
    raw_response_json,
    created_at,
    updated_at
`

type MarkDecisionAttemptFailedParams struct {
	ID              int64
	Status          string
	Recommendation  string
	Message         string
	CorrelationID   pgtype.Text
	AttemptCount    int32
	LastAttemptAt   pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	DiagnosticsJson []byte
	RawResponseJson []byte
}

func (q *Queries) MarkDecisionAttemptFailed(ctx context.Context, arg MarkDecisionAttemptFailedParams) (DecisionSnapshot, error) {
	row := q.db.QueryRow(ctx, markDecisionAttemptFailed,
		arg.ID,
		arg.Status,
		arg.Recommendation,
		arg.Message,
		arg.CorrelationID,
		arg.AttemptCount,
		arg.LastAttemptAt,
		arg.CompletedAt,
		arg.DiagnosticsJson,
		arg.RawResponseJson,
	)
	var i DecisionSnapshot
	err := row.Scan(
		&i.ID,
		&i.ExaminationID,
		&i.SpecialistID,
		&i.Status,
		&i.PayloadVersion,
		&i.AggregationVersion,
		&i.Recommendation,
		&i.Message,
		&i.CorrelationID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.CompletedAt,
		&i.DiagnosticsJson,
		&i.RawResponseJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDecisionAttemptSucceeded = `-- name: MarkDecisionAttemptSucceeded :one
UPDATE decision_snapshots
SET
    status = 'succeeded',
    recommendation = $2,
    message = $3,
    correlation_id = $4,
    attempt_count = $5,
    last_attempt_at = $6,
    completed_at = $7,
    diagnostics_json = $8,
    raw_response_json = $9,
    updated_at = NOW()
WHERE id = $1
RETURNING
    id,
    examination_id,
    specialist_id,
    status,
    payload_version,
    aggregation_version,
    recommendation,
    message,
    correlation_id,
    max_attempts,
    attempt_count,
    last_attempt_at,
    completed_at,
    diagnostics_json,
    raw_response_json,
    created_at,
    updated_at
`

type MarkDecisionAttemptSucceededParams struct {
	ID              int64
	Recommendation  string
	Message         string
	CorrelationID   pgtype.Text
	AttemptCount    int32
	LastAttemptAt   pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	DiagnosticsJson []byte
	RawResponseJson []byte
}

func (q *Queries) MarkDecisionAttemptSucceeded(ctx context.Context, arg MarkDecisionAttemptSucceededParams) (DecisionSnapshot, error) {
	row := q.db.QueryRow(ctx, markDecisionAttemptSucceeded,
		arg.ID,
		arg.Recommendation,
		arg.Message,
		arg.CorrelationID,
		arg.AttemptCount,
		arg.LastAttemptAt,
		arg.CompletedAt,
		arg.DiagnosticsJson,
		arg.RawResponseJson,
	)
	var i DecisionSnapshot
	err := row.Scan(
		&i.ID,
		&i.ExaminationID,
		&i.SpecialistID,
		&i.Status,
		&i.PayloadVersion,
		&i.AggregationVersion,
		&i.Recommendation,
		&i.Message,
		&i.CorrelationID,
		&i.MaxAttempts,
		&i.AttemptCount,
		&i.LastAttemptAt,
		&i.CompletedAt,
		&i.DiagnosticsJson,
		&i.RawResponseJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
