// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: examinations.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAnswersForExamination = `-- name: CountAnswersForExamination :one
SELECT COUNT(*)
FROM answers
WHERE examination_id = $1
`

func (q *Queries) CountAnswersForExamination(ctx context.Context, examinationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countAnswersForExamination, examinationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExaminationQuestions = `-- name: CountExaminationQuestions :one
SELECT COUNT(*)
FROM examination_questions
WHERE examination_id = $1
`

func (q *Queries) CountExaminationQuestions(ctx context.Context, examinationID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countExaminationQuestions, examinationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExamination = `-- name: CreateExamination :one
INSERT INTO examinations (
    specialist_id,
    created_by_user_id,
    questionnaire_id,
    status
) VALUES (
    $1, $2, $3, 'created'
)
RETURNING id, specialist_id, created_by_user_id, questionnaire_id, status, created_at, started_at, finished_at, updated_at
`

type CreateExaminationParams struct {
	SpecialistID    int64
	CreatedByUserID int64
	QuestionnaireID pgtype.Int8
}

type CreateExaminationRow struct {
	ID              int64
	SpecialistID    int64
	CreatedByUserID int64
	QuestionnaireID pgtype.Int8
	Status          string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) CreateExamination(ctx context.Context, arg CreateExaminationParams) (CreateExaminationRow, error) {
	row := q.db.QueryRow(ctx, createExamination, arg.SpecialistID, arg.CreatedByUserID, arg.QuestionnaireID)
	var i CreateExaminationRow
	err := row.Scan(
		&i.ID,
		&i.SpecialistID,
		&i.CreatedByUserID,
		&i.QuestionnaireID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createExaminationProcessingLaunch = `-- name: CreateExaminationProcessingLaunch :exec
INSERT INTO examination_processing_launches (
    examination_id
) VALUES (
    $1
)
ON CONFLICT DO NOTHING
`

func (q *Queries) CreateExaminationProcessingLaunch(ctx context.Context, examinationID int64) error {
	_, err := q.db.Exec(ctx, createExaminationProcessingLaunch, examinationID)
	return err
}

const createExaminationQuestionSnapshots = `-- name: CreateExaminationQuestionSnapshots :many
INSERT INTO examination_questions (
    examination_id,
    specialist_id,
    questionnaire_id,
    source_question_id,
    position,
    question_text
)
SELECT
    $1,
    $2,
    $3,
    qq.question_id,
    qq.position,
    q.text
FROM questionnaire_questions qq
JOIN questions q ON q.id = qq.question_id
WHERE qq.questionnaire_id = $3
ORDER BY qq.position
RETURNING id, examination_id, specialist_id, questionnaire_id, source_question_id, position, question_text
`

type CreateExaminationQuestionSnapshotsParams struct {
	ExaminationID   int64
	SpecialistID    int64
	QuestionnaireID int64
}

func (q *Queries) CreateExaminationQuestionSnapshots(ctx context.Context, arg CreateExaminationQuestionSnapshotsParams) ([]ExaminationQuestion, error) {
	rows, err := q.db.Query(ctx, createExaminationQuestionSnapshots, arg.ExaminationID, arg.SpecialistID, arg.QuestionnaireID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExaminationQuestion
	for rows.Next() {
		var i ExaminationQuestion
		if err := rows.Scan(
			&i.ID,
			&i.ExaminationID,
			&i.SpecialistID,
			&i.QuestionnaireID,
			&i.SourceQuestionID,
			&i.Position,
			&i.QuestionText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishExamination = `-- name: FinishExamination :one
UPDATE examinations
SET
    status = 'ready_for_processing',
    finished_at = COALESCE(finished_at, NOW()),
    updated_at = NOW()
WHERE id = $1
RETURNING id, specialist_id, created_by_user_id, questionnaire_id, status, created_at, started_at, finished_at, updated_at
`

type FinishExaminationRow struct {
	ID              int64
	SpecialistID    int64
	CreatedByUserID int64
	QuestionnaireID pgtype.Int8
	Status          string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) FinishExamination(ctx context.Context, id int64) (FinishExaminationRow, error) {
	row := q.db.QueryRow(ctx, finishExamination, id)
	var i FinishExaminationRow
	err := row.Scan(
		&i.ID,
		&i.SpecialistID,
		&i.CreatedByUserID,
		&i.QuestionnaireID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExaminationByID = `-- name: GetExaminationByID :one
SELECT id, specialist_id, created_by_user_id, questionnaire_id, status, created_at, started_at, finished_at, updated_at
FROM examinations
WHERE id = $1
`

type GetExaminationByIDRow struct {
	ID              int64
	SpecialistID    int64
	CreatedByUserID int64
	QuestionnaireID pgtype.Int8
	Status          string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetExaminationByID(ctx context.Context, id int64) (GetExaminationByIDRow, error) {
	row := q.db.QueryRow(ctx, getExaminationByID, id)
	var i GetExaminationByIDRow
	err := row.Scan(
		&i.ID,
		&i.SpecialistID,
		&i.CreatedByUserID,
		&i.QuestionnaireID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getExaminationForUpdate = `-- name: GetExaminationForUpdate :one
SELECT id, specialist_id, created_by_user_id, questionnaire_id, status, created_at, started_at, finished_at, updated_at
FROM examinations
WHERE id = $1
FOR UPDATE
`

type GetExaminationForUpdateRow struct {
	ID              int64
	SpecialistID    int64
	CreatedByUserID int64
	QuestionnaireID pgtype.Int8
	Status          string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetExaminationForUpdate(ctx context.Context, id int64) (GetExaminationForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getExaminationForUpdate, id)
	var i GetExaminationForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.SpecialistID,
		&i.CreatedByUserID,
		&i.QuestionnaireID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExaminationQuestionsByExaminationID = `-- name: ListExaminationQuestionsByExaminationID :many
SELECT id, examination_id, specialist_id, questionnaire_id, source_question_id, position, question_text
FROM examination_questions
WHERE examination_id = $1
ORDER BY position, id
`

func (q *Queries) ListExaminationQuestionsByExaminationID(ctx context.Context, examinationID int64) ([]ExaminationQuestion, error) {
	rows, err := q.db.Query(ctx, listExaminationQuestionsByExaminationID, examinationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExaminationQuestion
	for rows.Next() {
		var i ExaminationQuestion
		if err := rows.Scan(
			&i.ID,
			&i.ExaminationID,
			&i.SpecialistID,
			&i.QuestionnaireID,
			&i.SourceQuestionID,
			&i.Position,
			&i.QuestionText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExaminations = `-- name: ListExaminations :many
SELECT id, specialist_id, created_by_user_id, questionnaire_id, status, created_at, started_at, finished_at, updated_at
FROM examinations
ORDER BY created_at DESC, id DESC
`

type ListExaminationsRow struct {
	ID              int64
	SpecialistID    int64
	CreatedByUserID int64
	QuestionnaireID pgtype.Int8
	Status          string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListExaminations(ctx context.Context) ([]ListExaminationsRow, error) {
	rows, err := q.db.Query(ctx, listExaminations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExaminationsRow
	for rows.Next() {
		var i ListExaminationsRow
		if err := rows.Scan(
			&i.ID,
			&i.SpecialistID,
			&i.CreatedByUserID,
			&i.QuestionnaireID,
			&i.Status,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExaminationsBySpecialistID = `-- name: ListExaminationsBySpecialistID :many
SELECT id, specialist_id, created_by_user_id, questionnaire_id, status, created_at, started_at, finished_at, updated_at
FROM examinations
WHERE specialist_id = $1
ORDER BY created_at DESC, id DESC
`

type ListExaminationsBySpecialistIDRow struct {
	ID              int64
	SpecialistID    int64
	CreatedByUserID int64
	QuestionnaireID pgtype.Int8
	Status          string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListExaminationsBySpecialistID(ctx context.Context, specialistID int64) ([]ListExaminationsBySpecialistIDRow, error) {
	rows, err := q.db.Query(ctx, listExaminationsBySpecialistID, specialistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExaminationsBySpecialistIDRow
	for rows.Next() {
		var i ListExaminationsBySpecialistIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SpecialistID,
			&i.CreatedByUserID,
			&i.QuestionnaireID,
			&i.Status,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExaminationStatus = `-- name: UpdateExaminationStatus :one
UPDATE examinations
SET
    status = $2,
    started_at = CASE
        WHEN $2 = 'collecting_answers' AND started_at IS NULL THEN NOW()
        ELSE started_at
    END,
    finished_at = CASE
        WHEN $2 = 'ready_for_processing' THEN NOW()
        ELSE finished_at
    END,
    updated_at = NOW()
WHERE id = $1
RETURNING id, specialist_id, created_by_user_id, questionnaire_id, status, created_at, started_at, finished_at, updated_at
`

type UpdateExaminationStatusParams struct {
	ID     int64
	Status string
}

type UpdateExaminationStatusRow struct {
	ID              int64
	SpecialistID    int64
	CreatedByUserID int64
	QuestionnaireID pgtype.Int8
	Status          string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateExaminationStatus(ctx context.Context, arg UpdateExaminationStatusParams) (UpdateExaminationStatusRow, error) {
	row := q.db.QueryRow(ctx, updateExaminationStatus, arg.ID, arg.Status)
	var i UpdateExaminationStatusRow
	err := row.Scan(
		&i.ID,
		&i.SpecialistID,
		&i.CreatedByUserID,
		&i.QuestionnaireID,
		&i.Status,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.UpdatedAt,
	)
	return i, err
}
