// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Answer struct {
	ID              int64
	ExaminationID   int64
	CreatedByUserID int64
	AnswerText      string
	AudioS3Key      string
	CreatedAt       pgtype.Timestamptz
}

type Examination struct {
	ID              int64
	SpecialistID    int64
	CreatedByUserID int64
	Status          string
	CreatedAt       pgtype.Timestamptz
	StartedAt       pgtype.Timestamptz
	FinishedAt      pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	QuestionnaireID pgtype.Int8
}

type ExaminationQuestion struct {
	ID               int64
	ExaminationID    int64
	SpecialistID     int64
	QuestionnaireID  int64
	SourceQuestionID pgtype.Int8
	Position         int32
	QuestionText     string
}

type Question struct {
	ID        int64
	Text      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Questionnaire struct {
	ID          int64
	Title       string
	Description pgtype.Text
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type QuestionnaireQuestion struct {
	QuestionnaireID int64
	QuestionID      int64
	Position        int32
}

type RefreshSession struct {
	ID                  int64
	UserID              int64
	TokenHash           []byte
	ExpiresAt           pgtype.Timestamptz
	RevokedAt           pgtype.Timestamptz
	ReplacedBySessionID pgtype.Int8
	CreatedByIp         pgtype.Text
	UserAgent           pgtype.Text
	LastUsedAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

type Role struct {
	ID        int64
	Slug      string
	Name      string
	CreatedAt pgtype.Timestamptz
}

type Specialist struct {
	ID              int64
	FullName        string
	PersonnelNumber pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type User struct {
	ID           int64
	Login        string
	PasswordHash string
	RoleID       int64
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
