// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processing.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProcessingChannelRuns = `-- name: CreateProcessingChannelRuns :many
WITH mandatory_channels AS (
    SELECT
        unnest($2::text[]) AS channel
)
INSERT INTO examination_channel_runs (
    examination_id,
    channel,
    status,
    attempt_count,
    max_attempts,
    message_version
)
SELECT
    $1,
    mandatory_channels.channel,
    'pending',
    0,
    $3,
    $4
FROM mandatory_channels
JOIN examination_processing_launches launches
    ON launches.examination_id = $1
ON CONFLICT (examination_id, channel) DO UPDATE
SET
    max_attempts = EXCLUDED.max_attempts,
    message_version = EXCLUDED.message_version,
    updated_at = NOW()
RETURNING
    id,
    examination_id,
    channel,
    status,
    attempt_count,
    max_attempts,
    message_version,
    last_error_code,
    last_error_message,
    broker_message_id,
    broker_correlation_id,
    queued_at,
    started_at,
    finished_at,
    created_at,
    updated_at
`

type CreateProcessingChannelRunsParams struct {
	ExaminationID  int64
	Column2        []string
	MaxAttempts    int32
	MessageVersion int32
}

func (q *Queries) CreateProcessingChannelRuns(ctx context.Context, arg CreateProcessingChannelRunsParams) ([]ExaminationChannelRun, error) {
	rows, err := q.db.Query(ctx, createProcessingChannelRuns,
		arg.ExaminationID,
		arg.Column2,
		arg.MaxAttempts,
		arg.MessageVersion,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExaminationChannelRun
	for rows.Next() {
		var i ExaminationChannelRun
		if err := rows.Scan(
			&i.ID,
			&i.ExaminationID,
			&i.Channel,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.MessageVersion,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.BrokerMessageID,
			&i.BrokerCorrelationID,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createProcessingOutboxRows = `-- name: CreateProcessingOutboxRows :many
INSERT INTO processing_outbox (
    examination_id,
    channel_run_id,
    channel,
    exchange_name,
    routing_key,
    status,
    attempt_count,
    max_attempts,
    message_version,
    payload,
    broker_correlation_id
)
SELECT
    channel_runs.examination_id,
    channel_runs.id,
    channel_runs.channel,
    'processing.commands',
    CASE channel_runs.channel
        WHEN 'text' THEN 'processing.command.text'
        WHEN 'acoustic' THEN 'processing.command.acoustic'
        ELSE 'processing.command.paralinguistic'
    END,
    'pending',
    channel_runs.attempt_count,
    channel_runs.max_attempts,
    channel_runs.message_version,
    $2::jsonb,
    CASE channel_runs.channel
        WHEN 'text' THEN format('exam-%s-text-v%s', channel_runs.examination_id, channel_runs.message_version)
        WHEN 'acoustic' THEN format('exam-%s-acoustic-v%s', channel_runs.examination_id, channel_runs.message_version)
        ELSE format('exam-%s-paralinguistic-v%s', channel_runs.examination_id, channel_runs.message_version)
    END
FROM examination_channel_runs channel_runs
WHERE channel_runs.examination_id = $1
ON CONFLICT (channel_run_id) DO NOTHING
RETURNING
    id,
    examination_id,
    channel_run_id,
    channel,
    exchange_name,
    routing_key,
    status,
    attempt_count,
    max_attempts,
    message_version,
    payload,
    broker_message_id,
    broker_correlation_id,
    last_error_code,
    last_error_message,
    published_at,
    created_at,
    updated_at
`

type CreateProcessingOutboxRowsParams struct {
	ExaminationID int64
	Column2       []byte
}

func (q *Queries) CreateProcessingOutboxRows(ctx context.Context, arg CreateProcessingOutboxRowsParams) ([]ProcessingOutbox, error) {
	rows, err := q.db.Query(ctx, createProcessingOutboxRows, arg.ExaminationID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProcessingOutbox
	for rows.Next() {
		var i ProcessingOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ExaminationID,
			&i.ChannelRunID,
			&i.Channel,
			&i.ExchangeName,
			&i.RoutingKey,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.MessageVersion,
			&i.Payload,
			&i.BrokerMessageID,
			&i.BrokerCorrelationID,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExaminationProcessingProjection = `-- name: GetExaminationProcessingProjection :many
SELECT
    examinations.id AS examination_id,
    examinations.status AS examination_status,
    examinations.finished_at AS examination_finished_at,
    examinations.updated_at AS examination_updated_at,
    channel_runs.id AS channel_run_id,
    channel_runs.channel,
    channel_runs.status AS channel_status,
    channel_runs.attempt_count,
    channel_runs.max_attempts,
    channel_runs.message_version,
    channel_runs.last_error_code,
    channel_runs.last_error_message,
    channel_runs.broker_message_id,
    channel_runs.broker_correlation_id,
    channel_runs.queued_at,
    channel_runs.started_at,
    channel_runs.finished_at,
    processing_outbox.status AS outbox_status,
    processing_outbox.published_at,
    processing_outbox.updated_at AS outbox_updated_at
FROM examinations
LEFT JOIN examination_channel_runs channel_runs
    ON channel_runs.examination_id = examinations.id
LEFT JOIN processing_outbox
    ON processing_outbox.channel_run_id = channel_runs.id
WHERE examinations.id = $1
ORDER BY channel_runs.channel ASC
`

type GetExaminationProcessingProjectionRow struct {
	ExaminationID         int64
	ExaminationStatus     string
	ExaminationFinishedAt pgtype.Timestamptz
	ExaminationUpdatedAt  pgtype.Timestamptz
	ChannelRunID          pgtype.Int8
	Channel               pgtype.Text
	ChannelStatus         pgtype.Text
	AttemptCount          pgtype.Int4
	MaxAttempts           pgtype.Int4
	MessageVersion        pgtype.Int4
	LastErrorCode         pgtype.Text
	LastErrorMessage      pgtype.Text
	BrokerMessageID       pgtype.Text
	BrokerCorrelationID   pgtype.Text
	QueuedAt              pgtype.Timestamptz
	StartedAt             pgtype.Timestamptz
	FinishedAt            pgtype.Timestamptz
	OutboxStatus          pgtype.Text
	PublishedAt           pgtype.Timestamptz
	OutboxUpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetExaminationProcessingProjection(ctx context.Context, id int64) ([]GetExaminationProcessingProjectionRow, error) {
	rows, err := q.db.Query(ctx, getExaminationProcessingProjection, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExaminationProcessingProjectionRow
	for rows.Next() {
		var i GetExaminationProcessingProjectionRow
		if err := rows.Scan(
			&i.ExaminationID,
			&i.ExaminationStatus,
			&i.ExaminationFinishedAt,
			&i.ExaminationUpdatedAt,
			&i.ChannelRunID,
			&i.Channel,
			&i.ChannelStatus,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.MessageVersion,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.BrokerMessageID,
			&i.BrokerCorrelationID,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.OutboxStatus,
			&i.PublishedAt,
			&i.OutboxUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingProcessingOutboxRows = `-- name: ListPendingProcessingOutboxRows :many
SELECT
    id,
    examination_id,
    channel_run_id,
    channel,
    exchange_name,
    routing_key,
    status,
    attempt_count,
    max_attempts,
    message_version,
    payload,
    broker_message_id,
    broker_correlation_id,
    last_error_code,
    last_error_message,
    published_at,
    created_at,
    updated_at
FROM processing_outbox
WHERE status = 'pending'
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListPendingProcessingOutboxRows(ctx context.Context) ([]ProcessingOutbox, error) {
	rows, err := q.db.Query(ctx, listPendingProcessingOutboxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProcessingOutbox
	for rows.Next() {
		var i ProcessingOutbox
		if err := rows.Scan(
			&i.ID,
			&i.ExaminationID,
			&i.ChannelRunID,
			&i.Channel,
			&i.ExchangeName,
			&i.RoutingKey,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.MessageVersion,
			&i.Payload,
			&i.BrokerMessageID,
			&i.BrokerCorrelationID,
			&i.LastErrorCode,
			&i.LastErrorMessage,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
