// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questionnaires.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addQuestionToQuestionnaire = `-- name: AddQuestionToQuestionnaire :exec
INSERT INTO questionnaire_questions (
    questionnaire_id,
    question_id,
    position
) VALUES (
    $1, $2, $3
)
`

type AddQuestionToQuestionnaireParams struct {
	QuestionnaireID int64
	QuestionID      int64
	Position        int32
}

func (q *Queries) AddQuestionToQuestionnaire(ctx context.Context, arg AddQuestionToQuestionnaireParams) error {
	_, err := q.db.Exec(ctx, addQuestionToQuestionnaire, arg.QuestionnaireID, arg.QuestionID, arg.Position)
	return err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
    text
) VALUES (
    $1
)
RETURNING id, text, created_at, updated_at
`

func (q *Queries) CreateQuestion(ctx context.Context, text string) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion, text)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuestionnaire = `-- name: CreateQuestionnaire :one
INSERT INTO questionnaires (
    title,
    description,
    is_active,
    last_edited_by_user_id,
    last_edited_at
) VALUES (
    $1, $2, $3, $4, NOW()
)
RETURNING id, title, description, is_active, last_edited_by_user_id, last_edited_at, created_at, updated_at
`

type CreateQuestionnaireParams struct {
	Title              string
	Description        pgtype.Text
	IsActive           bool
	LastEditedByUserID pgtype.Int8
}

type CreateQuestionnaireRow struct {
	ID                 int64
	Title              string
	Description        pgtype.Text
	IsActive           bool
	LastEditedByUserID pgtype.Int8
	LastEditedAt       pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) CreateQuestionnaire(ctx context.Context, arg CreateQuestionnaireParams) (CreateQuestionnaireRow, error) {
	row := q.db.QueryRow(ctx, createQuestionnaire,
		arg.Title,
		arg.Description,
		arg.IsActive,
		arg.LastEditedByUserID,
	)
	var i CreateQuestionnaireRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.LastEditedByUserID,
		&i.LastEditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrphanQuestions = `-- name: DeleteOrphanQuestions :exec
DELETE FROM questions q
WHERE NOT EXISTS (
    SELECT 1
    FROM questionnaire_questions qq
    WHERE qq.question_id = q.id
)
`

func (q *Queries) DeleteOrphanQuestions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOrphanQuestions)
	return err
}

const deleteQuestionnaireQuestions = `-- name: DeleteQuestionnaireQuestions :exec
DELETE FROM questionnaire_questions
WHERE questionnaire_id = $1
`

func (q *Queries) DeleteQuestionnaireQuestions(ctx context.Context, questionnaireID int64) error {
	_, err := q.db.Exec(ctx, deleteQuestionnaireQuestions, questionnaireID)
	return err
}

const getQuestionnaireByID = `-- name: GetQuestionnaireByID :one
SELECT id, title, description, is_active, last_edited_by_user_id, last_edited_at, created_at, updated_at
FROM questionnaires
WHERE id = $1
`

type GetQuestionnaireByIDRow struct {
	ID                 int64
	Title              string
	Description        pgtype.Text
	IsActive           bool
	LastEditedByUserID pgtype.Int8
	LastEditedAt       pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) GetQuestionnaireByID(ctx context.Context, id int64) (GetQuestionnaireByIDRow, error) {
	row := q.db.QueryRow(ctx, getQuestionnaireByID, id)
	var i GetQuestionnaireByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.LastEditedByUserID,
		&i.LastEditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestionnaireDetailsByID = `-- name: GetQuestionnaireDetailsByID :many
SELECT
    q.id,
    q.title,
    q.description,
    q.is_active,
    usage_stats.usage_count,
    COALESCE(usage_stats.last_used_at, 'epoch'::timestamptz) AS last_used_at,
    q.last_edited_at,
    editor.id AS last_editor_user_id,
    editor.login AS last_editor_login,
    q.created_at,
    q.updated_at,
    qq.question_id,
    ques.text AS question_text,
    qq.position
FROM questionnaires q
LEFT JOIN (
    SELECT
        e.questionnaire_id,
        COUNT(*)::BIGINT AS usage_count,
        MAX(COALESCE(e.finished_at, e.started_at, e.created_at)) AS last_used_at
    FROM examinations e
    WHERE e.questionnaire_id IS NOT NULL
    GROUP BY e.questionnaire_id
) usage_stats ON usage_stats.questionnaire_id = q.id
LEFT JOIN users editor ON editor.id = q.last_edited_by_user_id
LEFT JOIN questionnaire_questions qq ON qq.questionnaire_id = q.id
LEFT JOIN questions ques ON ques.id = qq.question_id
WHERE q.id = $1
ORDER BY qq.position ASC
`

type GetQuestionnaireDetailsByIDRow struct {
	ID               int64
	Title            string
	Description      pgtype.Text
	IsActive         bool
	UsageCount       int64
	LastUsedAt       interface{}
	LastEditedAt     pgtype.Timestamptz
	LastEditorUserID pgtype.Int8
	LastEditorLogin  pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	QuestionID       pgtype.Int8
	QuestionText     pgtype.Text
	Position         pgtype.Int4
}

func (q *Queries) GetQuestionnaireDetailsByID(ctx context.Context, id int64) ([]GetQuestionnaireDetailsByIDRow, error) {
	rows, err := q.db.Query(ctx, getQuestionnaireDetailsByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuestionnaireDetailsByIDRow
	for rows.Next() {
		var i GetQuestionnaireDetailsByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.IsActive,
			&i.UsageCount,
			&i.LastUsedAt,
			&i.LastEditedAt,
			&i.LastEditorUserID,
			&i.LastEditorLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QuestionID,
			&i.QuestionText,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionnaireDetails = `-- name: ListQuestionnaireDetails :many
SELECT
    q.id,
    q.title,
    q.description,
    q.is_active,
    usage_stats.usage_count,
    COALESCE(usage_stats.last_used_at, 'epoch'::timestamptz) AS last_used_at,
    q.last_edited_at,
    editor.id AS last_editor_user_id,
    editor.login AS last_editor_login,
    q.created_at,
    q.updated_at,
    qq.question_id,
    ques.text AS question_text,
    qq.position
FROM questionnaires q
LEFT JOIN (
    SELECT
        e.questionnaire_id,
        COUNT(*)::BIGINT AS usage_count,
        MAX(COALESCE(e.finished_at, e.started_at, e.created_at)) AS last_used_at
    FROM examinations e
    WHERE e.questionnaire_id IS NOT NULL
    GROUP BY e.questionnaire_id
) usage_stats ON usage_stats.questionnaire_id = q.id
LEFT JOIN users editor ON editor.id = q.last_edited_by_user_id
LEFT JOIN questionnaire_questions qq ON qq.questionnaire_id = q.id
LEFT JOIN questions ques ON ques.id = qq.question_id
ORDER BY q.id DESC, qq.position ASC
`

type ListQuestionnaireDetailsRow struct {
	ID               int64
	Title            string
	Description      pgtype.Text
	IsActive         bool
	UsageCount       int64
	LastUsedAt       interface{}
	LastEditedAt     pgtype.Timestamptz
	LastEditorUserID pgtype.Int8
	LastEditorLogin  pgtype.Text
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	QuestionID       pgtype.Int8
	QuestionText     pgtype.Text
	Position         pgtype.Int4
}

func (q *Queries) ListQuestionnaireDetails(ctx context.Context) ([]ListQuestionnaireDetailsRow, error) {
	rows, err := q.db.Query(ctx, listQuestionnaireDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionnaireDetailsRow
	for rows.Next() {
		var i ListQuestionnaireDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.IsActive,
			&i.UsageCount,
			&i.LastUsedAt,
			&i.LastEditedAt,
			&i.LastEditorUserID,
			&i.LastEditorLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QuestionID,
			&i.QuestionText,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestionnaire = `-- name: UpdateQuestionnaire :one
UPDATE questionnaires
SET
    title = $2,
    description = $3,
    is_active = $4,
    last_edited_by_user_id = $5,
    last_edited_at = NOW(),
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, is_active, last_edited_by_user_id, last_edited_at, created_at, updated_at
`

type UpdateQuestionnaireParams struct {
	ID                 int64
	Title              string
	Description        pgtype.Text
	IsActive           bool
	LastEditedByUserID pgtype.Int8
}

type UpdateQuestionnaireRow struct {
	ID                 int64
	Title              string
	Description        pgtype.Text
	IsActive           bool
	LastEditedByUserID pgtype.Int8
	LastEditedAt       pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) UpdateQuestionnaire(ctx context.Context, arg UpdateQuestionnaireParams) (UpdateQuestionnaireRow, error) {
	row := q.db.QueryRow(ctx, updateQuestionnaire,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.IsActive,
		arg.LastEditedByUserID,
	)
	var i UpdateQuestionnaireRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.LastEditedByUserID,
		&i.LastEditedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
