// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: questionnaires.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addQuestionToQuestionnaire = `-- name: AddQuestionToQuestionnaire :exec
INSERT INTO questionnaire_questions (
    questionnaire_id,
    question_id,
    position
) VALUES (
    $1, $2, $3
)
`

type AddQuestionToQuestionnaireParams struct {
	QuestionnaireID int64
	QuestionID      int64
	Position        int32
}

func (q *Queries) AddQuestionToQuestionnaire(ctx context.Context, arg AddQuestionToQuestionnaireParams) error {
	_, err := q.db.Exec(ctx, addQuestionToQuestionnaire, arg.QuestionnaireID, arg.QuestionID, arg.Position)
	return err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
    text
) VALUES (
    $1
)
RETURNING id, text, created_at, updated_at
`

func (q *Queries) CreateQuestion(ctx context.Context, text string) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion, text)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createQuestionnaire = `-- name: CreateQuestionnaire :one
INSERT INTO questionnaires (
    title,
    description,
    is_active
) VALUES (
    $1, $2, $3
)
RETURNING id, title, description, is_active, created_at, updated_at
`

type CreateQuestionnaireParams struct {
	Title       string
	Description pgtype.Text
	IsActive    bool
}

func (q *Queries) CreateQuestionnaire(ctx context.Context, arg CreateQuestionnaireParams) (Questionnaire, error) {
	row := q.db.QueryRow(ctx, createQuestionnaire, arg.Title, arg.Description, arg.IsActive)
	var i Questionnaire
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOrphanQuestions = `-- name: DeleteOrphanQuestions :exec
DELETE FROM questions q
WHERE NOT EXISTS (
    SELECT 1
    FROM questionnaire_questions qq
    WHERE qq.question_id = q.id
)
`

func (q *Queries) DeleteOrphanQuestions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOrphanQuestions)
	return err
}

const deleteQuestionnaireQuestions = `-- name: DeleteQuestionnaireQuestions :exec
DELETE FROM questionnaire_questions
WHERE questionnaire_id = $1
`

func (q *Queries) DeleteQuestionnaireQuestions(ctx context.Context, questionnaireID int64) error {
	_, err := q.db.Exec(ctx, deleteQuestionnaireQuestions, questionnaireID)
	return err
}

const getQuestionnaireByID = `-- name: GetQuestionnaireByID :one
SELECT id, title, description, is_active, created_at, updated_at
FROM questionnaires
WHERE id = $1
`

func (q *Queries) GetQuestionnaireByID(ctx context.Context, id int64) (Questionnaire, error) {
	row := q.db.QueryRow(ctx, getQuestionnaireByID, id)
	var i Questionnaire
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestionnaireDetailsByID = `-- name: GetQuestionnaireDetailsByID :many
SELECT
    q.id,
    q.title,
    q.description,
    q.is_active,
    q.created_at,
    q.updated_at,
    qq.question_id,
    ques.text AS question_text,
    qq.position
FROM questionnaires q
LEFT JOIN questionnaire_questions qq ON qq.questionnaire_id = q.id
LEFT JOIN questions ques ON ques.id = qq.question_id
WHERE q.id = $1
ORDER BY qq.position ASC
`

type GetQuestionnaireDetailsByIDRow struct {
	ID           int64
	Title        string
	Description  pgtype.Text
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	QuestionID   pgtype.Int8
	QuestionText pgtype.Text
	Position     pgtype.Int4
}

func (q *Queries) GetQuestionnaireDetailsByID(ctx context.Context, id int64) ([]GetQuestionnaireDetailsByIDRow, error) {
	rows, err := q.db.Query(ctx, getQuestionnaireDetailsByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetQuestionnaireDetailsByIDRow
	for rows.Next() {
		var i GetQuestionnaireDetailsByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QuestionID,
			&i.QuestionText,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionnaireDetails = `-- name: ListQuestionnaireDetails :many
SELECT
    q.id,
    q.title,
    q.description,
    q.is_active,
    q.created_at,
    q.updated_at,
    qq.question_id,
    ques.text AS question_text,
    qq.position
FROM questionnaires q
LEFT JOIN questionnaire_questions qq ON qq.questionnaire_id = q.id
LEFT JOIN questions ques ON ques.id = qq.question_id
ORDER BY q.id DESC, qq.position ASC
`

type ListQuestionnaireDetailsRow struct {
	ID           int64
	Title        string
	Description  pgtype.Text
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	QuestionID   pgtype.Int8
	QuestionText pgtype.Text
	Position     pgtype.Int4
}

func (q *Queries) ListQuestionnaireDetails(ctx context.Context) ([]ListQuestionnaireDetailsRow, error) {
	rows, err := q.db.Query(ctx, listQuestionnaireDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionnaireDetailsRow
	for rows.Next() {
		var i ListQuestionnaireDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.QuestionID,
			&i.QuestionText,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestionnaire = `-- name: UpdateQuestionnaire :one
UPDATE questionnaires
SET
    title = $2,
    description = $3,
    is_active = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, is_active, created_at, updated_at
`

type UpdateQuestionnaireParams struct {
	ID          int64
	Title       string
	Description pgtype.Text
	IsActive    bool
}

func (q *Queries) UpdateQuestionnaire(ctx context.Context, arg UpdateQuestionnaireParams) (Questionnaire, error) {
	row := q.db.QueryRow(ctx, updateQuestionnaire,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.IsActive,
	)
	var i Questionnaire
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
