// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: specialists.sql

package sqlcdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSpecialist = `-- name: CreateSpecialist :one
INSERT INTO specialists (
    full_name,
    personnel_number
) VALUES (
    $1, $2
)
RETURNING id, full_name, personnel_number, created_at, updated_at
`

type CreateSpecialistParams struct {
	FullName        string
	PersonnelNumber pgtype.Text
}

func (q *Queries) CreateSpecialist(ctx context.Context, arg CreateSpecialistParams) (Specialist, error) {
	row := q.db.QueryRow(ctx, createSpecialist, arg.FullName, arg.PersonnelNumber)
	var i Specialist
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PersonnelNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSpecialist = `-- name: DeleteSpecialist :execrows
DELETE FROM specialists
WHERE id = $1
`

func (q *Queries) DeleteSpecialist(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSpecialist, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSpecialistByID = `-- name: GetSpecialistByID :one
SELECT id, full_name, personnel_number, created_at, updated_at
FROM specialists
WHERE id = $1
`

func (q *Queries) GetSpecialistByID(ctx context.Context, id int64) (Specialist, error) {
	row := q.db.QueryRow(ctx, getSpecialistByID, id)
	var i Specialist
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PersonnelNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSpecialists = `-- name: ListSpecialists :many
SELECT id, full_name, personnel_number, created_at, updated_at
FROM specialists
ORDER BY id DESC
`

func (q *Queries) ListSpecialists(ctx context.Context) ([]Specialist, error) {
	rows, err := q.db.Query(ctx, listSpecialists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Specialist
	for rows.Next() {
		var i Specialist
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.PersonnelNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpecialist = `-- name: UpdateSpecialist :one
UPDATE specialists
SET
    full_name = $2,
    personnel_number = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, full_name, personnel_number, created_at, updated_at
`

type UpdateSpecialistParams struct {
	ID              int64
	FullName        string
	PersonnelNumber pgtype.Text
}

func (q *Queries) UpdateSpecialist(ctx context.Context, arg UpdateSpecialistParams) (Specialist, error) {
	row := q.db.QueryRow(ctx, updateSpecialist, arg.ID, arg.FullName, arg.PersonnelNumber)
	var i Specialist
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PersonnelNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
